import {
  Member,
  Coach,
  FinanceEntry,
  FinanceSummary,
  DashboardStats,
  ClubSettings,
  UserProfile,
  Subscription,
} from '@/types';

// Mock Members Data
export const mockMembers: Member[] = [
  {
    id: '1',
    fullName: 'Marko Marković',
    dateOfBirth: '2012-03-15',
    age: 12,
    groupId: 'group1',
    groupName: 'U12 - Intermediate',
    gender: 'MALE',
    height: 152,
    weight: 45,
    position: 'Forward',
    paymentStatus: 'PAID',
    medicalStatus: 'VALID',
  },
  {
    id: '2',
    fullName: 'Ana Petrović',
    dateOfBirth: '2013-07-22',
    age: 11,
    groupId: 'group1',
    groupName: 'U12 - Intermediate',
    gender: 'FEMALE',
    height: 148,
    weight: 42,
    position: 'Midfielder',
    paymentStatus: 'PAID',
    medicalStatus: 'VALID',
  },
  {
    id: '3',
    fullName: 'Stefan Jovanović',
    dateOfBirth: '2014-01-10',
    age: 10,
    groupId: 'group2',
    groupName: 'U10 - Beginners',
    gender: 'MALE',
    height: 140,
    weight: 38,
    position: 'Defender',
    paymentStatus: 'UNPAID',
    medicalStatus: 'EXPIRED',
  },
  {
    id: '4',
    fullName: 'Milica Nikolić',
    dateOfBirth: '2012-09-05',
    age: 12,
    groupId: 'group3',
    groupName: 'U14 - Advanced',
    gender: 'FEMALE',
    height: 156,
    weight: 48,
    position: 'Goalkeeper',
    paymentStatus: 'PAID',
    medicalStatus: 'VALID',
  },
  {
    id: '5',
    fullName: 'Luka Đorđević',
    dateOfBirth: '2011-11-30',
    age: 13,
    groupId: 'group3',
    groupName: 'U14 - Advanced',
    gender: 'MALE',
    height: 165,
    weight: 55,
    position: 'Forward',
    paymentStatus: 'PAID',
    medicalStatus: 'VALID',
  },
  {
    id: '6',
    fullName: 'Jovana Stojanović',
    dateOfBirth: '2015-04-18',
    age: 9,
    groupId: 'group2',
    groupName: 'U10 - Beginners',
    gender: 'FEMALE',
    height: 135,
    weight: 35,
    position: 'Midfielder',
    paymentStatus: 'UNPAID',
    medicalStatus: 'VALID',
  },
  {
    id: '7',
    fullName: 'Nikola Ilić',
    dateOfBirth: '2010-06-25',
    age: 14,
    groupId: 'group4',
    groupName: 'U16 - Elite',
    gender: 'MALE',
    height: 172,
    weight: 62,
    position: 'Defender',
    paymentStatus: 'PAID',
    medicalStatus: 'VALID',
  },
  {
    id: '8',
    fullName: 'Teodora Pavlović',
    dateOfBirth: '2013-12-08',
    age: 11,
    groupId: 'group1',
    groupName: 'U12 - Intermediate',
    gender: 'FEMALE',
    height: 150,
    weight: 44,
    position: 'Forward',
    paymentStatus: 'PAID',
    medicalStatus: 'EXPIRED',
  },
];

// Mock Coaches Data
export const mockCoaches: Coach[] = [
  {
    id: '1',
    fullName: 'Dragan Stojković',
    email: 'dragan.stojkovic@4sports.rs',
    phoneNumber: '+381 64 123 4567',
    groupsCount: 3,
    contractExpiryDate: '2025-12-31',
    isExpiringSoon: false,
  },
  {
    id: '2',
    fullName: 'Jelena Radović',
    email: 'jelena.radovic@4sports.rs',
    phoneNumber: '+381 63 987 6543',
    groupsCount: 2,
    contractExpiryDate: '2025-01-15',
    isExpiringSoon: true,
  },
  {
    id: '3',
    fullName: 'Milan Obradović',
    email: 'milan.obradovic@4sports.rs',
    phoneNumber: '+381 65 555 7890',
    groupsCount: 1,
    contractExpiryDate: '2024-11-20',
    isExpiringSoon: true,
  },
  {
    id: '4',
    fullName: 'Sanja Popović',
    email: 'sanja.popovic@4sports.rs',
    phoneNumber: '+381 66 222 3333',
    groupsCount: 2,
    contractExpiryDate: '2026-06-30',
    isExpiringSoon: false,
  },
];

// Mock Finance Entries
export const mockFinanceEntries: FinanceEntry[] = [
  {
    id: '1',
    type: 'INCOME',
    category: 'Membership Payment',
    description: 'Mesečna članarina - Marko Marković',
    amount: 5000,
    date: '2025-12-01',
    recordedBy: 'Sistem',
    isManual: false,
    createdAt: '2025-12-01T10:00:00Z',
  },
  {
    id: '2',
    type: 'INCOME',
    category: 'Membership Payment',
    description: 'Mesečna članarina - Ana Petrović',
    amount: 5000,
    date: '2025-12-01',
    recordedBy: 'Sistem',
    isManual: false,
    createdAt: '2025-12-01T10:05:00Z',
  },
  {
    id: '3',
    type: 'INCOME',
    category: 'Registration Fee',
    description: 'Godišnja registracija - Nova sezona',
    amount: 15000,
    date: '2025-11-25',
    recordedBy: 'Dragan Stojković',
    isManual: true,
    createdAt: '2025-11-25T14:30:00Z',
  },
  {
    id: '4',
    type: 'EXPENSE',
    category: 'Equipment Purchase',
    description: 'Fudbalske lopte - 10 komada',
    amount: 25000,
    date: '2025-11-20',
    recordedBy: 'Dragan Stojković',
    isManual: true,
    createdAt: '2025-11-20T09:15:00Z',
  },
  {
    id: '5',
    type: 'EXPENSE',
    category: 'Facility Rent',
    description: 'Zakup terena - Novembar',
    amount: 80000,
    date: '2025-11-01',
    recordedBy: 'Dragan Stojković',
    isManual: true,
    createdAt: '2025-11-01T08:00:00Z',
  },
  {
    id: '6',
    type: 'INCOME',
    category: 'Sponsorship',
    description: 'Sponzorstvo - Lokalna firma ABC',
    amount: 50000,
    date: '2025-11-15',
    recordedBy: 'Dragan Stojković',
    isManual: true,
    createdAt: '2025-11-15T11:00:00Z',
  },
  {
    id: '7',
    type: 'EXPENSE',
    category: 'Coach Salary',
    description: 'Plata - Jelena Radović (Novembar)',
    amount: 45000,
    date: '2025-11-30',
    recordedBy: 'Sistem',
    isManual: true,
    createdAt: '2025-11-30T16:00:00Z',
  },
  {
    id: '8',
    type: 'INCOME',
    category: 'Membership Payment',
    description: 'Mesečna članarina - Luka Đorđević',
    amount: 5000,
    date: '2025-12-01',
    recordedBy: 'Sistem',
    isManual: false,
    createdAt: '2025-12-01T10:10:00Z',
  },
  {
    id: '9',
    type: 'EXPENSE',
    category: 'Utilities',
    description: 'Struja i voda - Novembar',
    amount: 12000,
    date: '2025-11-28',
    recordedBy: 'Dragan Stojković',
    isManual: true,
    createdAt: '2025-11-28T13:00:00Z',
  },
  {
    id: '10',
    type: 'INCOME',
    category: 'Tournament Prize',
    description: 'Nagrada sa turnira - Zimski kup',
    amount: 30000,
    date: '2025-11-10',
    recordedBy: 'Milan Obradović',
    isManual: true,
    createdAt: '2025-11-10T18:00:00Z',
  },
];

// Mock Finance Summary
export const mockFinanceSummary: FinanceSummary = {
  totalIncome: 210000,
  totalExpenses: 162000,
  netProfit: 48000,
  currentMonthIncome: 85000,
  currentMonthExpenses: 45000,
};

// Mock Dashboard Stats
export const mockDashboardStats: DashboardStats = {
  currentRevenue: 85000,
  newMembersPercentage: 15,
  totalMembers: 8,
  totalTransactions: 10,
  memberGrowth: [
    { month: 'Jan', count: 5 },
    { month: 'Feb', count: 6 },
    { month: 'Mar', count: 7 },
    { month: 'Apr', count: 7 },
    { month: 'May', count: 8 },
    { month: 'Jun', count: 10 },
    { month: 'Jul', count: 12 },
    { month: 'Aug', count: 15 },
    { month: 'Sep', count: 18 },
    { month: 'Oct', count: 20 },
    { month: 'Nov', count: 22 },
    { month: 'Dec', count: 24 },
  ],
  balanceData: {
    income: 210000,
    expense: 162000,
  },
  quarterlyRevenue: [
    { quarter: 'Q1', amount: 45000 },
    { quarter: 'Q2', amount: 52000 },
    { quarter: 'Q3', amount: 58000 },
    { quarter: 'Q4', amount: 55000 },
  ],
  monthlyFinance: [
    { month: 'Jan', revenue: 35000, expenses: 28000 },
    { month: 'Feb', revenue: 38000, expenses: 30000 },
    { month: 'Mar', revenue: 42000, expenses: 32000 },
    { month: 'Apr', revenue: 45000, expenses: 35000 },
    { month: 'May', revenue: 48000, expenses: 38000 },
    { month: 'Jun', revenue: 52000, expenses: 40000 },
    { month: 'Jul', revenue: 55000, expenses: 42000 },
    { month: 'Aug', revenue: 58000, expenses: 45000 },
    { month: 'Sep', revenue: 60000, expenses: 48000 },
    { month: 'Oct', revenue: 62000, expenses: 50000 },
    { month: 'Nov', revenue: 65000, expenses: 52000 },
    { month: 'Dec', revenue: 68000, expenses: 55000 },
  ],
};

// Mock Club Settings
export const mockClubSettings: ClubSettings = {
  id: '1',
  clubName: '4Sports Football Academy',
  address: 'Bulevar Oslobođenja 123, Novi Sad 21000',
  phoneNumber: '+381 21 123 4567',
  email: 'info@4sports.rs',
  logoUrl: undefined,
};

// Mock User Profile
export const mockUserProfile: UserProfile = {
  id: '1',
  fullName: 'Dragan Stojković',
  email: 'dragan.stojkovic@4sports.rs',
  phoneNumber: '+381 64 123 4567',
  profileImage: undefined,
  role: 'ADMIN',
};

// Mock Subscription
export const mockSubscription: Subscription = {
  plan: 'FREE',
  memberLimit: 50,
  currentMembersCount: 8,
  validUntil: undefined,
};
